
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: furima_39942_development

test:
  <<: *default
  database: furima_39942_test

production:
  <<: *default
  database: furima_39942_production
  username: furima_39942
  password: <%= ENV["FURIMA_39942_DATABASE_PASSWORD"] %>
